### ISSUE TITLE
Produces collection wrapper but fail on bind.

### ISSUE THREAD

**Issue by ioArchman** [scisci/go-mobile-collection#1]
Hi @scisci - Tried the generator utility and got the file produced. But just ran into trouble while running 

```
go mobile bind -target=ios
```

as it failed. I was looking forward to get the collection of 'person' available for ObjC. Am I doing anything wrong ?  Any thoughts?

Attached are the files (a simple struct and an export function) and below is the stack trace.

```
gomobile: darwin-armv7: go build -p=8 -pkgdir=/Users/bob/gowork/pkg/gomobile/pkg_darwin_arm -tags="" -buildmode=c-archive -tags=ios -o /var/folders/_w/kb0xmwm51hg3gvtbcc3sz74xbk9c3p/T/gomobile-work-962964218/CollectionManager-arm.a /var/folders/_w/kb0xmwm51hg3gvtbcc3sz74xbk9c3p/T/gomobile-work-962964218/src/iosbin/main.go failed: exit status 2
# _/var/folders/_w/kb0xmwm51hg3gvtbcc3sz74xbk9c3p/T/gomobile-work-962964218/src/go_CollectionManager
/var/folders/_w/kb0xmwm51hg3gvtbcc3sz74xbk9c3p/T/gomobile-work-962964218/src/go_CollectionManager/go_CollectionManagermain.go:8: imported and not used: "golang.org/x/mobile/bind/seq"
/var/folders/_w/kb0xmwm51hg3gvtbcc3sz74xbk9c3p/T/gomobile-work-962964218/src/go_CollectionManager/go_CollectionManagermain.go:9: imported and not used: "research.com/CollectionPOC" as CollectionManager
```

[gocodefiles.zip](https://github.com/scisci/go-mobile-collection/files/101863/gocodefiles.zip)

**Comment by scisci** [comment]
You need to uppercase your structs/fields so they are exported and accessible by iOS.

try it with:

```
struct Person {
  Name string
  Age string
}
```

I believe what's causing the bug is the error is that you have an exported method (SocialWorkers) that returns an unexported type (personCollection). When you uppercase it should fix this. Let me know.

**Comment by ioArchman** [comment]
when uppercased, I got the below:

```
gomobile: unsupported, direct named type research.com/CollectionPOC.PersonCollection: struct{s []*research.com/CollectionPOC.Person}
```

updated files attached.
[gocodefiles.zip](https://github.com/scisci/go-mobile-collection/files/101957/gocodefiles.zip)

**Comment by scisci** [comment]
Aha, another gotcha from gomobile. You can only expose pointers to structs, not the values.

`func SocialWorkers() PersonCollection`

change that to

`func SocialWorkers() *PersonCollection`

and hopefully that works

gomobile has some of the most unhelpful error messages ever.

**Comment by ioArchman** [comment]
yeah, you are right. It works now! Thanks.
